### ISSUE TITLE
setPan() implemented?

### ISSUE THREAD

**Issue by toyfoo** [roymacdonald/ofxSoundObjects#13] opened 2017-05-07 04:44 UTC
I'm using ofxSoundObjects for mixing and routing audio to different audio devices simultaneously. It works mostly neatly. The issue is that I can't get setPan() to work. 

```
player.setPan(0.99);
player.play();

```
Doesn't seem have any effect, both on stereo and mono files. With the same files, it does work using the standard ofSoundPlayer. This issue both occurs on macOS and on debian (RasberryPi). 

Are there undocumented limitations or requirements for setPan(), or is this not implemented yet?

**Comment by roymacdonald** [comment] 2017-05-07 13:44
Him
It should work.
this seems to be a bug. I'll ckeck it and fix it. I'll let you know once done.
Thnaks.

**Comment by roymacdonald** [comment] 2017-05-08 02:24
Hey @toyfoo Just fixed it. It was a bug in ofxBasicSoundPlayer. Please let me know if it works as expected for you.
All the best!

**Comment by toyfoo** [comment] 2017-05-09 11:06
Hi @roymacdonald 
Thanks for the swift reaction! The 'example-soundPlayerObject' project does not seem to compile:
in ofApp.h: 
`ofxBasicSoundPlayer player;`
gives error "Field type 'ofxBasicSoundPlayer' is an abstract class"

in addons.make
needs line
`ofxGui`

cheers

**Comment by roymacdonald** [comment] 2017-05-09 13:21
Hi @toyfoo sorry for that. I fixed both. 
The abstract class error is because I'm using openframeworks at the current github version.
If you are using an older version it is probably the cause. I added a fix for this, please let me know if it works well now.
best

**Comment by toyfoo** [comment] 2017-05-09 14:46
@roymacdonald Thanks! Good info that the latest version on github works. Just to let you know, there are a few more errors now that popped up using 0.9.8. So I tried using the openframeworks github version, but encountered a few compile errors. It doesn't seem that straightforward :)

I got your updated code working by removing all uses of (the recently updated) ofxGui in the example code and xcode project and using these lines for testing purposes
`stream.setup(2,0, player.getSoundFile().getSampleRate(), 256, 1);
player.setPan(-1.0);`

Very helpful, thanks!

**Comment by roymacdonald** [comment] 2017-05-09 15:26
Hi, 
good to know. 
What errors did you get with OF's github version?
It is strange that you had to remove ofxGui.
that way of setting up the sound stream is deprecated that's why I changed it. It was that what was giving you problems? sounds strange.
best

**Comment by toyfoo** [comment] 2017-05-10 09:43
ok, so I cloned openframeworks freshly from github, downloaded the libraries
cloned ofxSoundObjects.git to the addons. 
running example-soundPlayerObject results in the following messages
```
building file list ... rsync: link_stat "/Users/tlaureyssens/dev/openFrameworks/addons/ofxSoundObjects/example-soundPlayerObject/../../../libs/glut/lib/osx/GLUT.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```
the solution is to rebuild the project xcode file using projectGenerator, and then it runs fine! 

removing ofxGui is only necessary in 0.9.8, check it out. 

cheers

**Comment by roymacdonald** [comment] 2017-05-10 12:28
HI, thanks for the info. 
Right, usually rebuilding the projects with project generator fixes a lot of problems. 
I will remove the projects from this repo, that way each person can create the correct project using PG.
best

**Closed** 2017-08-09 12:41 UTC
